### ISSUE TITLE
Cannot use sveltestrap in Sapper project

### ISSUE THREAD

**Issue by metacoding** [bestguy/sveltestrap#173]
I have a project created by Sapper and I have included the bootstrap css in my template. In my header component I used the Navbar (copied from the StoryBook sample https://sveltestrap.js.org/?path=/story/components--navbar) Now when I start the app I don't see any build error but when the app renders in browser I see the following error:

![image](https://user-images.githubusercontent.com/16768266/91095256-f973a080-e653-11ea-96c6-0efc3cd6b958.png)

`Error: <Navbar> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules
    at validate_component (C:\Users\mehra\Documents\my-sample\__sapper__\dev\server\server.js:226:15)
    at create_ssr_component (C:\Users\mehra\Documents\my-sample\__sapper__\dev\server\server.js:663:12)
    at Object.$$render (C:\Users\mehra\Documents\my-sample\__sapper__\dev\server\server.js:244:22)
    at create_ssr_component (C:\Users\mehra\Documents\my-sample\__sapper__\dev\server\server.js:716:45)
    at Object.$$render (C:\Users\mehra\Documents\my-sample\__sapper__\dev\server\server.js:244:22)
    at create_ssr_component (C:\Users\mehra\Documents\my-sample\__sapper__\dev\server\server.js:1013:40)
    at $$render (C:\Users\mehra\Documents\my-sample\__sapper__\dev\server\server.js:244:22)
    at Object.render (C:\Users\mehra\Documents\my-sample\__sapper__\dev\server\server.js:252:26)
    at handle_page (C:\Users\mehra\Documents\my-sample\__sapper__\dev\server\server.js:3506:36)`

**Comment by bestguy** [comment]
Hi @metacoding , please see note here for SSR:

https://github.com/bestguy/sveltestrap#note-on-server-side-rendering-ssr-usage-fixed

the recommendation was to import component directly.

**Comment by bestguy** [comment]
Closing as above should resolve, please reopen if I've misunderstood issue
