### ISSUE TITLE
how to use with sapper?

### ISSUE THREAD

**Issue by rohanrajpal** [bestguy/sveltestrap#196]
Hey, I'm new to web dev and started off with sapper. However, I can't get my head around where should I import the bootstrap CSS file?

So far I have done
```bash
npx degit "sveltejs/sapper-template#rollup" my-app
cd my-app

npm install

npm install --save sveltestrap svelte
```
I import the css in `template.html`
```html
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
```
Then I pasted the following in `src/routes/index.svelte`
```svelte
<script>
  import { Button } from 'sveltestrap';
  const handleClick = () => alert('I warned you!');
</script>

<Button color="danger" on:click={handleClick}>Do Not Press</Button>
```

All the above steps give me the error:
```
Error: <Button> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules
    at validate_component (/home/rohan/Documents/sapper-app/node_modules/svelte/internal/index.mjs:1318:18)
    at /home/rohan/Documents/sapper-app/__sapper__/dev/server/server.js:280:3
    at Object.$$render (/home/rohan/Documents/sapper-app/node_modules/svelte/internal/index.mjs:1341:23)
    at Object.default (/home/rohan/Documents/sapper-app/src/node_modules/@sapper/internal/App.svelte:24:50)
    at /home/rohan/Documents/sapper-app/__sapper__/dev/server/server.js:407:66
    at Object.$$render (/home/rohan/Documents/sapper-app/node_modules/svelte/internal/index.mjs:1341:23)
    at /home/rohan/Documents/sapper-app/src/node_modules/@sapper/internal/App.svelte:20:18
    at $$render (/home/rohan/Documents/sapper-app/node_modules/svelte/internal/index.mjs:1341:23)
    at Object.render (/home/rohan/Documents/sapper-app/node_modules/svelte/internal/index.mjs:1349:33)
    at /home/rohan/Documents/sapper-app/src/node_modules/@sapper/server.mjs:4687:54
```
So which js file should import the bootstrap CSS?

**Comment by bestguy** [comment]
Hi, there is a note on SSR usage on the home page, near the bottom: https://sveltestrap.js.org

**Comment by rohanrajpal** [comment]
> Hi, for that error there is a note on SSR usage on the home page, near the bottom: https://sveltestrap.js.org
> 
> For adding Bootstrap CSS, see the same page under "Adding Bootstrap"

How did I miss that! Importing the component directly fixed it for me. Thanks :smile:

**Comment by bestguy** [comment]
Feel free to reopen if see further issues
